version: "3.7" # 目前使用的版本，可以參考官網：
services: # services 關鍵字後面列出 web, redis 兩項專案中的服務
  Website:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile # Build 在同一資料夾的 Dockerfile（描述 Image 要組成的 yaml 檔案）成 container
    image: jordan007/iviti-wa:v120
    container_name: iviti-wa
    environment:
      - NGINX_PORT=8120
      - BACKEND_PORT=6632
      - STREAM_PORT=8083
    command: >
      /bin/sh -c
      "envsubst '
      $${NGINX_PORT}
      $${BACKEND_PORT}
      $${STREAM_PORT}
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    network_mode: host

